default: &default
  adapter: postgresql
  encoding: unicode
  database: silicon_balls
  pool: 25
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: silicon_balls_test

production:
  <<: *default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
