default: &default
  adapter: mysql2
  database: silicon_balls
  pool: 25
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: silicon_balls_test

production:
  <<: *default
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
