default:
  adapter: postgresql
  encoding: unicode
  database: silicon_balls
  pool: 25
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: silicon_balls
  pool: 25
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: silicon_balls_test
  pool: 25
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: silicon_balls
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
